### ISSUE TITLE
noob setup context

### ISSUE THREAD

**Issue by roycewilliams** [cyclone-github/argon_cracker#1]
It would be useful to provide some install / dependency breadcrumbs for noobs, for stuff like:

$ go get ./...
/home/royce/go/src/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.go:9:8: C source files not allowed when not using cgo or SWIG: cpu_gccgo_x86.c

**Comment by cyclone-github** [comment]
Thanks for the feedback. I have included a high level, generic how-to on compiling Go source code linked in the README.
https://github.com/cyclone-github/scripts/blob/main/intro_to_go.txt

The README also references a Go compiler script I've written which automates the process of compiling Go source code.
https://github.com/cyclone-github/scripts/blob/main/go_compiler.sh

For a more specific how-to for compiling argon_cracker (this may be slightly different depending on your OS or prefered compiling options):
1. _make sure Go is installed and cd to working directory where argon_cracker.go is located_
2. `go mod init argon_cracker.go`
3. `go mod tidy`
4. `go build -ldflags="-s -w" argon_cracker.go`
5. `./argon_cracker -h {hash file} -w {wordlist file}`

**Comment by roycewilliams** [comment]
Hey, thanks - very helpful! That got me quite a ways, but still encountering the error above - I assumed it was a simple dependency issue.

**Comment by roycewilliams** [comment]
For those playing along at home, this was due in part to me being on a very old version of Go - latest Go cleared up my error. :D
